image: Visual Studio 2017

# if the build is on master - 1.2.0
# if the build is on a branch - 1.2.0-branch+sha

version: '1.2.1'

init:
  - ps: $env:project="Envoy"
  - ps: $env:ver = if ($env:APPVEYOR_REPO_BRANCH -eq "master") { "$env:APPVEYOR_BUILD_VERSION" } else { "$env:APPVEYOR_BUILD_VERSION-$env:APPVEYOR_REPO_BRANCH+$env:APPVEYOR_REPO_COMMIT" }
  - ps: Update-AppveyorBuild -Version $env:ver
  
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
  - cmd: dotnet --version
  - cmd: dotnet --info

build_script:
  - cmd: dotnet restore ./src/{project}/{project}.csproj --verbosity m
  - cmd: dotnet build -c Release ./src/{project}/{project}.csproj

test_script:
  - cmd: dotnet restore ./src/{project}.Tests/{project}.Tests.csproj --verbosity m
  - cmd: dotnet test ./src/{project}.Tests/{project}.Tests.csproj

artifacts:
- path: .\src\**\*.nupkg
  name: NuGet

deploy:
  - provider: NuGet
    api_key:
      secure: 39TiDru9R2WsPYRl1ng1z5NQbI6A8tw+KfFlOE5KdT/4cTzKPlu8mjIud50s4Xce
    skip_symbols: false
    artifact: NuGet
    on:
      branch: master
      appveyor_repo_tag: true