version: '0.1.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
build_script:
  - cmd: cd src
  - cmd: dotnet --info
  - cmd: dotnet restore
  - cmd: dotnet build ./Envoy/Envoy.csproj -c Release --verbose
  - cmd: dotnet pack ./Envoy/Envoy.csproj -c Release --verbose
test_script:
  - cmd: dotnet test ./Envoy.Tests/Envoy.Tests.csproj
artifacts:
  - path: '**\*.nupkg'
    name: NuGetPackages
deploy:
  - provider: NuGet
    api_key:
      secure: 39TiDru9R2WsPYRl1ng1z5NQbI6A8tw+KfFlOE5KdT/4cTzKPlu8mjIud50s4Xce
    skip_symbols: false
    artifact: Envoy.nupkg
notifications:
  - provider: Email
    to:
      - peterkneale+envoy@gmail.com
    subject: 'Envoy: Build {{status}}'                 
    message: "{{message}}, {{commitId}}, ..."
    on_build_status_changed: true