image: Visual Studio 2017

version: '1.2.0'

init:
  - ps: $env:ver = if ($env:APPVEYOR_REPO_TAG -eq $True) { "$env:APPVEYOR_BUILD_VERSION-$env:APPVEYOR_BUILD_NUMBER" } else { "$env:APPVEYOR_BUILD_VERSION-$env:APPVEYOR_REPO_BRANCH-$env:APPVEYOR_BUILD_NUMBER" }
  - ps: Update-AppveyorBuild -Version $env:ver
  
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
  - cmd: dotnet --version
  - cmd: dotnet --info

build_script:
  - cmd: dotnet restore ./src/Envoy/Envoy.csproj --verbosity m
  - cmd: dotnet build -c Release ./src/Envoy/Envoy.csproj

test_script:
  - cmd: dotnet restore ./src/Envoy.Tests/Envoy.Tests.csproj --verbosity m
  - cmd: dotnet test ./src/Envoy.Tests/Envoy.Tests.csproj

artifacts:
- path: .\src\**\*.nupkg
  name: NuGet

deploy:
  - provider: NuGet
    api_key:
      secure: 39TiDru9R2WsPYRl1ng1z5NQbI6A8tw+KfFlOE5KdT/4cTzKPlu8mjIud50s4Xce
    skip_symbols: false
    artifact: NuGet
    on:
      branch: master                # release from master branch only
      appveyor_repo_tag: true       # deploy on tag push only