image: Visual Studio 2017

version: '1.2.1'

init:
  - ps: $env:project="Envoy"
  - ps: $env:sha = $env:APPVEYOR_REPO_COMMIT.Substring(0, 10)
  - ps: $env:branch = $env:APPVEYOR_REPO_BRANCH
  - ps: $env:version = $env:APPVEYOR_BUILD_VERSION
    # if the build is on master - 1.2.0
    # if the build is on a branch - 1.2.0-branch+sha
  - ps: $env:semver = if ($env:branch -eq "master") { "$env:version" } else { "$env:version-$env:branch+$env:sha" }
  - ps: Update-AppveyorBuild -Version $env:semver
  
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{semver}'

before_build:
  - cmd: dotnet --version
  - cmd: dotnet --info

build_script:
  - cmd: dotnet restore ./src/{project}/{project}.csproj --verbosity m
  - cmd: dotnet build -c Release ./src/{project}/{project}.csproj

test_script:
  - cmd: dotnet restore ./src/{project}.Tests/{project}.Tests.csproj --verbosity m
  - cmd: dotnet test ./src/{project}.Tests/{project}.Tests.csproj

artifacts:
- path: .\src\**\*.nupkg
  name: NuGet

deploy:
  - provider: NuGet
    api_key:
      secure: 39TiDru9R2WsPYRl1ng1z5NQbI6A8tw+KfFlOE5KdT/4cTzKPlu8mjIud50s4Xce
    skip_symbols: false
    artifact: NuGet
    on:
      branch: master
      appveyor_repo_tag: true