image: Visual Studio 2017

version: '1.2.2'

init:
  - ps: $env:version = $env:APPVEYOR_BUILD_VERSION
  - ps: $env:branch = $env:APPVEYOR_REPO_BRANCH
  - ps: $env:sha = $env:APPVEYOR_REPO_COMMIT.Substring(0, 7)
  - ps: $env:tagged = $env:APPVEYOR_REPO_TAG
  - ps: >-
      if ($env:branch -ne "master" -Or $env:tagged -ne "true")
      {
        # version-branch-sha
        $env:info = "$env:version-$env:branch-$env:sha"
        Update-AppveyorBuild -Version $env:info
      }

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{info}'

build_script:
  - cmd: dotnet restore ./src/Envoy/Envoy.csproj --verbosity m
  - cmd: dotnet build -c Release ./src/Envoy/Envoy.csproj

test_script:
  - cmd: dotnet restore ./src/Envoy.Tests/Envoy.Tests.csproj --verbosity m
  - cmd: dotnet test ./src/Envoy.Tests/Envoy.Tests.csproj

artifacts:
- path: .\src\**\*.nupkg
  name: NuGet

deploy:
  - provider: NuGet
    api_key:
      secure: 39TiDru9R2WsPYRl1ng1z5NQbI6A8tw+KfFlOE5KdT/4cTzKPlu8mjIud50s4Xce
    skip_symbols: false
    artifact: NuGet
    on:
      branch: master
      appveyor_repo_tag: true